apiVersion: v1
kind: Service
metadata:
  name: teleport-auth
  namespace: vassyutovich
spec:
  selector:
    app: teleport-auth
  ports:
    - name: auth
      port: 443
      targetPort: 443
      protocol: TCP
  type: ClusterIP
