apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport-proxy-config
  namespace: vassyutovich
data:
  teleport.yaml: |
    teleport:
      nodename: proxy
      data_dir: /var/lib/teleport
      connection_limits:
        max_connections: 100
        max_users: 50
      auth_servers:
        - teleport-auth:443
      auth_token: TeSt-t0ken
      log:
        output: stdout
        severity: DEBUG
    proxy_service:
      enabled: yes

      listen_addr: 0.0.0.0:3023
      ssh_public_addr: teleport-proxy-ssh-vassyutovich.mindbox.ru:443

      web_listen_addr: 0.0.0.0:3080
      public_addr: teleport-proxy-webssh-vassyutovich.mindbox.ru:443

      tunnel_listen_addr: 0.0.0.0:3024
      tunnel_public_addr: teleport-proxy-tunnel-vassyutovich.mindbox.ru:443
    auth_service:
      enabled: false
    ssh_service:
      enabled: false